# Generated by Django 4.2 on 2026-06-04 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('programme', models.TextField()),
                ('photo_campagne', models.ImageField(blank=True, null=True, upload_to='campagnes/')),
                ('numero_candidat', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('RETRAIT_DEMANDE', 'Retrait demandé'), ('RETIREE', 'Retirée')], default='EN_ATTENTE', max_length=30)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('motif_retrait', models.TextField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='elections.election')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='authentication.etudiant')),
            ],
            options={
                'verbose_name': 'Candidature',
                'db_table': 'candidatures',
                'ordering': ['numero_candidat'],
                'unique_together': {('etudiant', 'election')},
            },
        ),
    ]
