# Generated by Django 4.2 on 2026-07-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0002_alter_candidature_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='programme_fichier',
            field=models.FileField(blank=True, null=True, upload_to='programmes/'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='programme',
            field=models.TextField(blank=True, default=''),
        ),
    ]
