# Generated by Django 4.2 on 2026-06-04 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0001_initial'),
        ('elections', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('nb_inscrits', models.PositiveIntegerField(default=0)),
                ('nb_votants', models.PositiveIntegerField(default=0)),
                ('taux_participation', models.FloatField(default=0.0)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='elections.election')),
                ('generateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports', to='authentication.administrateur')),
            ],
            options={
                'verbose_name': 'Rapport',
                'db_table': 'rapports',
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nb_voix', models.PositiveIntegerField(default=0)),
                ('pourcentage', models.FloatField(default=0.0)),
                ('est_elu', models.BooleanField(default=False)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='candidatures.candidature')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='elections.election')),
            ],
            options={
                'verbose_name': 'Résultat',
                'db_table': 'resultats',
                'ordering': ['-nb_voix'],
                'unique_together': {('election', 'candidat')},
            },
        ),
    ]
