# Generated by Django 4.2 on 2026-06-04 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('CANDIDAT', 'Candidat'), ('ADMINISTRATEUR', 'Administrateur')], default='ETUDIANT', max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'db_table': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_admin', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'db_table': 'administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_etudiant', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('annee_academique', models.CharField(max_length=20)),
                ('a_vote', models.BooleanField(default=False)),
                ('vote_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'db_table': 'etudiants',
            },
        ),
        migrations.CreateModel(
            name='Visage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_embedding', models.BinaryField()),
                ('date_encodage', models.DateTimeField(auto_now_add=True)),
                ('modele_utilise', models.CharField(default='face_recognition', max_length=100)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visage', to='authentication.etudiant')),
            ],
            options={
                'verbose_name': 'Visage',
                'db_table': 'visages',
            },
        ),
    ]
