# Generated by Django 4.2 on 2026-06-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_utilisateur_email_verifie_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20)),
                ('est_inscrit', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Étudiant Autorisé',
                'db_table': 'etudiants_autorises',
            },
        ),
    ]
