# Generated by Django 4.2 on 2026-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_webauthncredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
    ]
