# Generated by Django 4.2 on 2026-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_utilisateur_est_supprime'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricule', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('code_otp', models.CharField(max_length=6)),
                ('date_expiration', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscription Temporaire',
                'db_table': 'inscriptions_temporaires',
            },
        ),
    ]
