# Generated by Django 4.2 on 2026-06-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_inscriptiontemporaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptiontemporaire',
            name='otp_verifie',
            field=models.BooleanField(default=False),
        ),
    ]
