# Generated by Django 4.2 on 2026-06-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_inscriptiontemporaire_otp_verifie'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptiontemporaire',
            name='webauthn_challenge',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
