# Generated by Django 4.2 on 2026-06-04 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0001_initial'),
        ('elections', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('adresse_blockchain', models.CharField(blank=True, max_length=255, null=True)),
                ('est_confirme', models.BooleanField(default=False)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes_recus', to='candidatures.candidature')),
                ('electeur', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vote', to='authentication.etudiant')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='elections.election')),
            ],
            options={
                'verbose_name': 'Vote',
                'db_table': 'votes',
            },
        ),
        migrations.CreateModel(
            name='TransactionVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('etudiant_hash', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bloc_numero', models.PositiveIntegerField(blank=True, null=True)),
                ('est_valide', models.BooleanField(default=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='candidatures.candidature')),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='votes.vote')),
            ],
            options={
                'verbose_name': 'Transaction Vote',
                'db_table': 'transactions_votes',
            },
        ),
    ]
