from django.urls import path
from .views import (
    InscriptionView,
    ConnexionView,
    EncodageVisageView,
    VerificationVisageView,
    ProfilView,
    DeconnexionView,
    EnvoyerOTPView,
    VerifierOTPView,
    EtudiantAutoriseListView,
    EtudiantAutoriseDetailView,
    ImportExcelEtudiantsView,
    GestionUtilisateursView,
    GestionUtilisateurDetailView,
    RestaurerUtilisateurView,
    SupprimerDefinitivementView,
    WebAuthnRegisterBeginView,
    CompleterInscriptionView,
    WebAuthnRegisterBeginPublicView,
    WebAuthnRegisterCompleteView,
    WebAuthnVerifyBeginView,
    WebAuthnVerifyCompleteView,
    MotDePasseOublieView,
    ReinitialisierMotDePasseView,
    PreInscriptionView,
    FinaliserInscriptionView,
)

urlpatterns = [
    path('inscription/',                           InscriptionView.as_view(),                name='inscription'),
    path('pre-inscription/',                       PreInscriptionView.as_view(),              name='pre-inscription'),
    path('finaliser-inscription/',                 FinaliserInscriptionView.as_view(),        name='finaliser-inscription'),
    path('connexion/',                             ConnexionView.as_view(),                   name='connexion'),
    path('deconnexion/',                           DeconnexionView.as_view(),                 name='deconnexion'),
    path('face/encoder/',                          EncodageVisageView.as_view(),              name='face-encoder'),
    path('face/verifier/',                         VerificationVisageView.as_view(),          name='face-verifier'),
    path('profil/',                                ProfilView.as_view(),                      name='profil'),
    path('otp/envoyer/',                           EnvoyerOTPView.as_view(),                  name='otp-envoyer'),
    path('otp/verifier/',                          VerifierOTPView.as_view(),                 name='otp-verifier'),
    path('mot-de-passe-oublie/',                   MotDePasseOublieView.as_view(),            name='mot-de-passe-oublie'),
    path('reinitialiser-mot-de-passe/',            ReinitialisierMotDePasseView.as_view(),    name='reinitialiser-mot-de-passe'),
    path('etudiants-autorises/',                   EtudiantAutoriseListView.as_view(),        name='etudiants-autorises'),
    path('etudiants-autorises/<int:pk>/',          EtudiantAutoriseDetailView.as_view(),      name='etudiant-autorise-detail'),
    path('etudiants-autorises/import/',            ImportExcelEtudiantsView.as_view(),        name='etudiants-autorises-import'),
    path('utilisateurs/',                          GestionUtilisateursView.as_view(),         name='utilisateurs'),
    path('utilisateurs/<uuid:user_id>/',           GestionUtilisateurDetailView.as_view(),    name='utilisateur-detail'),
    path('utilisateurs/<uuid:user_id>/supprimer-definitivement/', SupprimerDefinitivementView.as_view(), name='utilisateur-supprimer-definitif'),
    path('utilisateurs/<uuid:user_id>/restaurer/', RestaurerUtilisateurView.as_view(),        name='utilisateur-restaurer'),
    path('webauthn/register/begin-public/', WebAuthnRegisterBeginPublicView.as_view(), name='webauthn-register-begin-public'),
    path('completer-inscription/', CompleterInscriptionView.as_view(), name='completer-inscription'),
    path('webauthn/register/begin/',               WebAuthnRegisterBeginView.as_view(),       name='webauthn-register-begin'),
    path('webauthn/register/complete/',            WebAuthnRegisterCompleteView.as_view(),    name='webauthn-register-complete'),
    path('webauthn/verify/begin/',                 WebAuthnVerifyBeginView.as_view(),         name='webauthn-verify-begin'),
    path('webauthn/verify/complete/',              WebAuthnVerifyCompleteView.as_view(),      name='webauthn-verify-complete'),
]
