# Generated by Django 4.2 on 2026-06-04 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('annee_academique', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('CLOTUREE', 'Clôturée'), ('RESULTATS_PUBLIES', 'Résultats publiés')], default='PLANIFIEE', max_length=30)),
                ('contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elections_creees', to='authentication.administrateur')),
            ],
            options={
                'verbose_name': 'Élection',
                'db_table': 'elections',
                'ordering': ['-date_creation'],
            },
        ),
    ]
