# Generated by Django 4.2 on 2026-06-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='statut',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('CLOTUREE', 'Clôturée'), ('RESULTATS_PUBLIES', 'Résultats publiés'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=30),
        ),
    ]
